export const ScrollResource = [
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/logical-and-analytical-reasoning.png", name: "Aptitude" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/mongodb.png", name: "MongoDB" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/javascript.png", name: "Javascript" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/python.png", name: "Python" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/nodejs.png", name: "Nodejs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/sql.png", name: "SQL" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/reactjs.png", name: "Reactjs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/machine-learning.png", name: "Machine Learning" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/data-science.png", name: "Data Science" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/c.png", name: "C" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/cpp.png", name: "C++" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/java.png", name: "Java" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/logical-and-analytical-reasoning.png", name: "Aptitude" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/mongodb.png", name: "MongoDB" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/javascript.png", name: "Javascript" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/python.png", name: "Python" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/nodejs.png", name: "Nodejs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/sql.png", name: "SQL" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/reactjs.png", name: "Reactjs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/machine-learning.png", name: "Machine Learning" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/data-science.png", name: "Data Science" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/c.png", name: "C" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/cpp.png", name: "C++" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/java.png", name: "Java" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/logical-and-analytical-reasoning.png", name: "Aptitude" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/mongodb.png", name: "MongoDB" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/javascript.png", name: "Javascript" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/python.png", name: "Python" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/nodejs.png", name: "Nodejs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/sql.png", name: "SQL" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/reactjs.png", name: "Reactjs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/machine-learning.png", name: "Machine Learning" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/data-science.png", name: "Data Science" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/c.png", name: "C" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/cpp.png", name: "C++" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/java.png", name: "Java" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/logical-and-analytical-reasoning.png", name: "Aptitude" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/mongodb.png", name: "MongoDB" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/javascript.png", name: "Javascript" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/python.png", name: "Python" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/nodejs.png", name: "Nodejs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/sql.png", name: "SQL" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/reactjs.png", name: "Reactjs" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/machine-learning.png", name: "Machine Learning" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/data-science.png", name: "Data Science" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/c.png", name: "C" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/cpp.png", name: "C++" },
  { src: "https://cdn-media-assets.socratease.co/equip/product/img/homepage/skills-icons/java.png", name: "Java" },

];
